version: "3"

services:
  base-image:
    container_name: ${PREFIX}_base-image
    image: ${PREFIX}/base-image
    build:
      context: base-image
      args:
        - ORIGIN_IMAGE
        - OS_CODENAME
